USE [master]

/****** Object:  Database [template]    Script Date: 20/08/2024 19:41:10 ******/
CREATE DATABASE [template]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'template', FILENAME = N'C:\dev\s23087_Inzynierka_2024\database\template\template.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'template_log', FILENAME = N'C:\dev\s23087_Inzynierka_2024\database\template\log\template_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [template].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [template] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [template] SET ANSI_NULLS OFF 

ALTER DATABASE [template] SET ANSI_PADDING OFF 


ALTER DATABASE [template] SET ANSI_WARNINGS OFF 


ALTER DATABASE [template] SET ARITHABORT OFF 


ALTER DATABASE [template] SET AUTO_CLOSE OFF 


ALTER DATABASE [template] SET AUTO_SHRINK OFF 


ALTER DATABASE [template] SET AUTO_UPDATE_STATISTICS ON 


ALTER DATABASE [template] SET CURSOR_CLOSE_ON_COMMIT OFF 


ALTER DATABASE [template] SET CURSOR_DEFAULT  GLOBAL 


ALTER DATABASE [template] SET CONCAT_NULL_YIELDS_NULL OFF 


ALTER DATABASE [template] SET NUMERIC_ROUNDABORT OFF 


ALTER DATABASE [template] SET QUOTED_IDENTIFIER OFF 


ALTER DATABASE [template] SET RECURSIVE_TRIGGERS OFF 


ALTER DATABASE [template] SET  DISABLE_BROKER 


ALTER DATABASE [template] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 


ALTER DATABASE [template] SET DATE_CORRELATION_OPTIMIZATION OFF 


ALTER DATABASE [template] SET TRUSTWORTHY OFF 


ALTER DATABASE [template] SET ALLOW_SNAPSHOT_ISOLATION OFF 


ALTER DATABASE [template] SET PARAMETERIZATION SIMPLE 


ALTER DATABASE [template] SET READ_COMMITTED_SNAPSHOT OFF 


ALTER DATABASE [template] SET HONOR_BROKER_PRIORITY OFF 


ALTER DATABASE [template] SET RECOVERY FULL 


ALTER DATABASE [template] SET  MULTI_USER 


ALTER DATABASE [template] SET PAGE_VERIFY CHECKSUM  


ALTER DATABASE [template] SET DB_CHAINING OFF 


ALTER DATABASE [template] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 


ALTER DATABASE [template] SET TARGET_RECOVERY_TIME = 60 SECONDS 


ALTER DATABASE [template] SET DELAYED_DURABILITY = DISABLED 


ALTER DATABASE [template] SET ACCELERATED_DATABASE_RECOVERY = OFF  


ALTER DATABASE [template] SET QUERY_STORE = ON


ALTER DATABASE [template] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)


ALTER DATABASE [template] SET  READ_WRITE 


